pipelines:
  docker-python2-gide:
    group: stcdev
    label_template: "${git[:8]}"
    materials:
      git:
        git: "git@git.ai-traders.com:stcdev/docker-python2-gide.git"
        branch: master
      python2ide:
        pipeline: docker-python2-ide
        stage: publish
    stages:
      - validate:
          clean_workspace: true
          jobs:
            verify_version:
              resources:
                - docker_builder
              tasks:
               - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - ./tasks verify_version
      - build:
          clean_workspace: true
          jobs:
            py27:
              resources:
                - docker_builder
              artifacts:
                - build:
                    source: image/imagerc*
                    destination:
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build_py27
            py35:
              resources:
                - docker_builder
              artifacts:
                - build:
                    source: image/imagerc*
                    destination:
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build_py35
      - itest:
          clean_workspace: true
          jobs:
            py27:
              resources:
                - docker_builder
              tasks:
                - fetch:
                    stage: build
                    job: py27
                    is_file: yes
                    source: imagerc.py27
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks itest_py27
            py35:
              resources:
                - docker_builder
              tasks:
                - fetch:
                    stage: build
                    job: py35
                    is_file: yes
                    source: imagerc.py35
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks itest_py35
      - release:
          clean_workspace: true
          jobs:
            code:
              resources:
                - docker_builder
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks code_release
      - publish:
          clean_workspace: true
          jobs:
            py27:
              resources:
                - docker_builder
              tasks:
                - fetch:
                    stage: build
                    job: py27
                    is_file: yes
                    source: imagerc.py27
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks publish_py27
            py35:
              resources:
                - docker_builder
              tasks:
                - fetch:
                    stage: build
                    job: py35
                    is_file: yes
                    source: imagerc.py35
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks publish_py35
