pipelines:
  docker-python2-gide:
    group: stcdev
    label_template: "${git[:8]}"
    materials:
      git:
        git: "git@git.ai-traders.com:stcdev/docker-python2-gide.git"
        branch: master
      python2ide:
        pipeline: docker-python2-ide
        stage: publish
    stages:
      - validate:
          clean_workspace: true
          jobs:
            verify_version:
              resources:
                - docker_builder
              tasks:
               - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - ./tasks verify_version
      - build:
          clean_workspace: true
          jobs:
            py2:
              resources:
                - docker_builder
              artifacts:
                - build:
                    source: image/imagerc*
                    destination:
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build_py2
            py3:
              resources:
                - docker_builder
              artifacts:
                - build:
                    source: image/imagerc*
                    destination:
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build_py3
      - itest:
          clean_workspace: true
          jobs:
            py2:
              resources:
                - docker_builder
              tasks:
                - fetch:
                    stage: build
                    job: py2
                    is_file: yes
                    source: imagerc.py2-gdojo
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks itest_py2
            py3:
              resources:
                - docker_builder
              tasks:
                - fetch:
                    stage: build
                    job: py3
                    is_file: yes
                    source: imagerc.py3-gdojo
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks itest_py3
      - release:
          clean_workspace: true
          jobs:
            code:
              resources:
                - docker_builder
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks code_release
      - publish:
          clean_workspace: true
          jobs:
            py2:
              resources:
                - docker_builder
              tasks:
                - fetch:
                    stage: build
                    job: py2
                    is_file: yes
                    source: imagerc.py2-gdojo
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks publish_py2
            py3:
              resources:
                - docker_builder
              tasks:
                - fetch:
                    stage: build
                    job: py3
                    is_file: yes
                    source: imagerc.py3-gdojo
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks publish_py3
