# {{BASE_IMAGE_VERSION}} must be replaced with existing git tag.
# I added {{ }} so that docker build fails if it is not replaced.
FROM docker-registry.ai-traders.com/python2-ide:{{BASE_IMAGE_VERSION}}

# * locales package is 16MB but at least we have locale configured
# * dpkg-reconfigure --frontend=noninteractive locales -- for already installed
# packages
# * without xauth installed, we get "xvfb-run: error: xauth command not found"
# when using xvfb-run
RUN apt-get update &&\
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  locales &&\
  echo 'LANG="en_US.UTF-8"'>/etc/default/locale &&\
  locale-gen en_US.UTF-8 &&\
  update-locale LANG=C.UTF-8 &&\
  dpkg-reconfigure --frontend=noninteractive locales  &&\
  DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
  wget curl libxrender1 libxi6 libgconf-2-4 libfreetype6 libxtst6 xfce4 gnome-icon-theme

# original link: https://download.jetbrains.com/python/pycharm-community-2018.3.2.tar.gz
RUN echo 'Downloading Pycharm' &&\
  wget --quiet --progress=bar:force --no-check-certificate http://http.archive.ai-traders.com/files/pycharm/pycharm-community-2018.3.2.tar.gz -O /tmp/pycharm-community.tar.gz &&\
  echo 'Installing Pycharm' &&\
  mkdir -p /opt/pycharm &&\
  cd /tmp && tar -xf /tmp/pycharm-community.tar.gz &&\
  rm -r /tmp/pycharm-community.tar.gz &&\
  mv pycharm-community-*/* /opt/pycharm &&\
  rm /tmp/pycharm-* -r &&\
  ln -s /opt/pycharm/bin/pycharm.sh /usr/local/bin/pycharm

ENTRYPOINT ["/usr/bin/entrypoint.sh"]
CMD ["pycharm & /bin/bash"]

COPY etc_ide.d/scripts/* /etc/ide.d/scripts/

ARG this_image_tag_arg
ARG this_image_name_arg
ENV this_image_tag=${this_image_tag_arg} this_image_name=${this_image_name_arg}
